#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://127.0.0.1:4000}"

SESSION_JSON=$(curl -sS -X POST "$BASE_URL/api/v1/sessions" \
  -H 'Content-Type: application/json' \
  -d '{"title":"Sample Session"}')

SESSION_ID=$(echo "$SESSION_JSON" | sed -n 's/.*"id":\([0-9]\+\).*/\1/p' | head -n1)
if [[ -z "$SESSION_ID" ]]; then
  echo "Failed to create session: $SESSION_JSON"
  exit 1
fi

SAMPLE_PDF="/tmp/sample_session.pdf"
node - <<'NODE'
const fs = require('fs');
const PDFDocument = require('pdfkit');

const output = '/tmp/sample_session.pdf';
const doc = new PDFDocument({ size: 'A4', margin: 50 });
doc.pipe(fs.createWriteStream(output));
doc.fontSize(16).text('Document-analyzer-rag Sample PDF');
doc.moveDown();
doc.fontSize(12).text('This PDF is generated by scripts/load_sample_session.sh for indexing checks.');
doc.end();
NODE

UPLOAD_RESPONSE=$(curl -sS -X POST "$BASE_URL/api/v1/sessions/$SESSION_ID/pdfs" \
  -F "title=Sample PDF" \
  -F "file=@$SAMPLE_PDF;type=application/pdf")

echo "Session response: $SESSION_JSON"
echo "Upload response: $UPLOAD_RESPONSE"
